"""initial schema

Revision ID: b63086460908
Revises:
Create Date: 2026-09-19 16:44:31.280717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b63086460908'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('timezone', sa.String(length=64), server_default='UTC', nullable=False),
    sa.Column('quiet_hours_start', sa.Time(), nullable=True),
    sa.Column('quiet_hours_end', sa.Time(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('email = lower(email)', name=op.f('ck_users_email_lowercase')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('notification_channels',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('email', 'telegram', name='channeltype', native_enum=False, length=24), nullable=False),
    sa.Column('address', sa.String(length=320), nullable=False),
    sa.Column('priority', sa.Integer(), server_default='100', nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notification_channels_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_channels')),
    sa.UniqueConstraint('user_id', 'type', 'address', name=op.f('uq_notification_channels_user_id'))
    )
    op.create_index(op.f('ix_notification_channels_user_id'), 'notification_channels', ['user_id'], unique=False)
    op.create_table('push_subscriptions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh', sa.String(length=255), nullable=False),
    sa.Column('auth', sa.String(length=255), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_push_subscriptions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_push_subscriptions')),
    sa.UniqueConstraint('endpoint', name=op.f('uq_push_subscriptions_endpoint'))
    )
    op.create_index(op.f('ix_push_subscriptions_user_id'), 'push_subscriptions', ['user_id'], unique=False)
    op.create_table('tags',
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.Enum('car', 'pet', 'other', name='tagkind', native_enum=False, length=24), nullable=False),
    sa.Column('public_note', sa.String(length=280), nullable=True),
    sa.Column('photo_url', sa.String(length=2048), nullable=True),
    sa.Column('status', sa.Enum('active', 'paused', 'revoked', name='tagstatus', native_enum=False, length=24), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_tags_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags')),
    sa.UniqueConstraint('public_id', name=op.f('uq_tags_public_id'))
    )
    op.create_index(op.f('ix_tags_owner_id'), 'tags', ['owner_id'], unique=False)
    op.create_table('blocks',
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_blocks_tag_id_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blocks')),
    sa.UniqueConstraint('tag_id', 'ip_hash', name=op.f('uq_blocks_tag_id'))
    )
    op.create_index(op.f('ix_blocks_tag_id'), 'blocks', ['tag_id'], unique=False)
    op.create_table('scans',
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.Column('scan_token', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.String(length=40), nullable=False),
    sa.Column('message', sa.String(length=280), nullable=True),
    sa.Column('lat', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('lng', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=False),
    sa.Column('ua_hash', sa.String(length=64), nullable=False),
    sa.Column('risk_score', sa.Float(), server_default='0', nullable=False),
    sa.Column('status', sa.Enum('queued', 'notified', 'failed', 'suppressed', name='scanstatus', native_enum=False, length=24), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('lat BETWEEN -90 AND 90', name=op.f('ck_scans_lat_range')),
    sa.CheckConstraint('lng BETWEEN -180 AND 180', name=op.f('ck_scans_lng_range')),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_scans_tag_id_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scans')),
    sa.UniqueConstraint('scan_token', name=op.f('uq_scans_scan_token'))
    )
    op.create_index('ix_scans_created_at', 'scans', ['created_at'], unique=False)
    op.create_index('ix_scans_tag_id_created_at', 'scans', ['tag_id', 'created_at'], unique=False)
    op.create_table('deliveries',
    sa.Column('scan_id', sa.Uuid(), nullable=False),
    sa.Column('subscription_id', sa.Uuid(), nullable=True),
    sa.Column('channel_id', sa.Uuid(), nullable=True),
    sa.Column('channel', sa.Enum('webpush', 'email', 'telegram', name='deliverychannel', native_enum=False, length=24), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sent', 'failed', 'dead', name='deliverystatus', native_enum=False, length=24), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(subscription_id IS NOT NULL) <> (channel_id IS NOT NULL)', name=op.f('ck_deliveries_exactly_one_target')),
    sa.ForeignKeyConstraint(['channel_id'], ['notification_channels.id'], name=op.f('fk_deliveries_channel_id_notification_channels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name=op.f('fk_deliveries_scan_id_scans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['push_subscriptions.id'], name=op.f('fk_deliveries_subscription_id_push_subscriptions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deliveries')),
    sa.UniqueConstraint('scan_id', 'channel_id', name='uq_deliveries_scan_channel'),
    sa.UniqueConstraint('scan_id', 'subscription_id', name='uq_deliveries_scan_subscription')
    )
    op.create_table('replies',
    sa.Column('scan_id', sa.Uuid(), nullable=False),
    sa.Column('preset_key', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name=op.f('fk_replies_scan_id_scans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_replies')),
    sa.UniqueConstraint('scan_id', name=op.f('uq_replies_scan_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('replies')
    op.drop_table('deliveries')
    op.drop_index('ix_scans_tag_id_created_at', table_name='scans')
    op.drop_index('ix_scans_created_at', table_name='scans')
    op.drop_table('scans')
    op.drop_index(op.f('ix_blocks_tag_id'), table_name='blocks')
    op.drop_table('blocks')
    op.drop_index(op.f('ix_tags_owner_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_push_subscriptions_user_id'), table_name='push_subscriptions')
    op.drop_table('push_subscriptions')
    op.drop_index(op.f('ix_notification_channels_user_id'), table_name='notification_channels')
    op.drop_table('notification_channels')
    op.drop_table('users')
    # ### end Alembic commands ###
